services:
  - docker:19.03.7-dind
stages:
  - build jar
  - build and push docker image
  - deploy
build:
  image: maven:3.6.3-jdk-11-slim
  stage: build jar
  tags:
    - r1
  before_script:
    - source .env
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
deploy:
  image: docker:18.09.8
  stage: deploy
  before_script:
    - source .env
  tags:
    - r1
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
    - docker stop $APP_NAME
    - docker system prune -a -f
    - docker pull $DOCKER_REPO
    - docker container run -d --name $APP_NAME -p $PORT $DOCKER_REPO
    - docker logout
