stages:
  - build
  - deploy

main-build:
  image: maven:3.6.3-jdk-11-slim
  stage: build
  tags:
    - dev2-server
  script:
    - mvn clean install && mvn package -B -e
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

main-deploy:
  image: ubuntu:21.04
  stage: deploy
  tags:
    - dev2-server
  script:
    - mv target/*.jar /home/dev/opt/springcicd.jar
    - sudo systemctl restart springcicd.service
  only:
    - main
  dependencies:
    - main-build
