services:
  - docker:19.03.7-dind
stages:
  - build jar
  - build and push docker image
  - deploy
build:
  image: maven:3.6.3-jdk-11-slim
  stage: build jar
  tags:
    - shell-1
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
docker build:
  image: docker:stable
  stage: build and push docker image
  tags:
    - shell-1
  script:
    - docker build -t hoat35999/cicd .
    - docker login -u hoat35999 -p 01653693151 docker.io
    - docker push hoat35999/cicd
deploy:
  image: ubuntu:latest
  stage: deploy
  tags:
    - shell-1
  script:
    - docker login -u hoat35999 -p 01653693151 docker.io
    - docker system prune -a -f
    - docker pull hoat35999/cicd
    - docker container run -d --name hoat-cicd -p 8080 hoat35999/cicd
    - docker logout
